# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7cb8a374ca2ecbcc891eb61edd2cef09b5bd347ba72b01604c94a19de139848aae23c6490ec2f9bdd3260b51399c7ffcdacf2438ee3b9b8ab8821c88cd07e38

test:
  secret_key_base: 825805d20803b1fc202f0b488c69da3a52ec7b477b142836fe8e87cf2b54bd9fecd6f27c24fea1467f85e4eb0f2f75cffb4b428385ed264d00908c8b0e4ad9a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
